# This uses newer and faster docker based build system
sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 7.0

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

before_script:
  # Install composer packages before trying to activate themes or plugins
  - composer install

  # Start web server
  - cp wp-tests/lib/router.php web/router.php
  - php -S 0.0.0.0:12000 router.php &

  # Convert bedrock folder layout to traditional wp layout
  - cp -r web/wp/* web/
  - cp -r web/app web/wp-content

  # Delete duplicate content
  - rm -r web/{wp,app}

  - curl -i localhost:12000

#script:
#  - cd wp-tests/spec && bundle exec rspec test.rb
