# This uses newer and faster docker based build system
sudo: false

language: php

services:
  - mysql

notifications:
  on_success: never
  on_failure: change

# add PRODUCTION_SERVER_USER and PRODUCTION_SERVER_IP env to our context
secure: "Mw5fEyi2PnLV7lU9ljzkDgX9kb0MYWR9cqhQWtRy8OZowEpszFHaN+1/N05XfPoJ/rk4h9qIepldyWvTnxCQYfuJcZnQEF+98MHNSrSIEsatgpLuOAX0u62REKgHIvtnoqd6/rDDLbKLbu6WfSjksZ+FvTbXlYNEk0D5rTpzO/g93Dn3TlE+nNTXOR6NLsrF2jsdvXTOJYrew3nZMKKlZaXcHZXJ2orbIqa0H15xDLb66QEMEGAFYJUpnJxWfkWlQEM/+EImSjYLvoSjMxYrC3pqQcKxyZqIYiLRk21whU6OhKlmmAOFQSEkI8tcQVTeW+7/2qbfUTUGUe2QllaI+s/Lgrlb1+nlTNPSpefh4/EmzR4oZUWhdw4xfg43KVFXcvFZ49I1dPPL8S89cMY70Iy4hitXrfZydZjl/lkyVXFCKaWZNQhOvIJ36WjnKr9WmHJ40bcHQGOG0ei6pHIDinZfPjZadJO2Fxe6enOFMYY9Vbvu9fHG2gZ9dKPLC0P3Auz8oTzFzhMVDmAgdVlFE5GwGLpVZAqDvbvXbQkwSPDoQcScAet0BgHPRrkXyCE2AyEAp4ZV2rGhP6zjQuJIGQ0mS8699HHFyr16TEJZgM7bM204+gTPPjSZgFdZzeUJaaOuT5YEeOp4lsnVsUz+wxeTbX56M+Z6Nb7i49W/WT8="

php:
  - 7.0

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

before_script:
  # Encrypt ssh deploy key
  # This was done by: $ travis encrypt-file wordpress-rsa
  - openssl aes-256-cbc -K $encrypted_d54f28eb6d20_key -iv $encrypted_d54f28eb6d20_iv -in wordpress-rsa.enc -out wordpress-rsa -d

  # Install composer packages before trying to activate themes or plugins
  - composer install

  # Start web server
  - cp wp-tests/lib/router.php web/router.php

  # Convert bedrock folder layout to traditional wp layout
  - cp -r web/wp/* web/
  - cp -r web/app web/wp-content

  # Delete duplicate content
  - rm -r web/{wp,app}

  # Start wordpress
  - cd web
  - php -S 0.0.0.0:12000 router.php &
  - cd ..

  # Setup database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wordpress;'
  - mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY '25911661b5cd8309fad14674d9382d4d045d821334f93353';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'wordpress'@'localhost';"
  - mysql -e 'FLUSH PRIVILEGES;'

  # Install WP-CLI and wordpress database
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar wp-cli.phar
  - php wp-cli.phar core install --url=$WP_TEST_URL --title='Test' --admin_user=$WP_TEST_USER --admin_password=$WP_TEST_USER_PASS --admin_email="$WP_TEST_USER@wordpress.dev"

script:
  # Check that WP returns 200
  - curl -i localhost:12000 | grep 200

  # Copy all files to production using our private key
  - rsync -e "ssh -i wordpress-rsa" web --delete --exclude wp-content/uploads web $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER_IP:/var/www/html/







